
server:
  port: ${env.APPLICATION_PORT:8080}
  servlet:
    context-path: "/car-rental"

spring:
  application:
    name: car-rental-api
  datasource:
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"
  show-actuator: true

api:
  security:
    token:
      secret: ${env.JWT_SECRET:my-secret-key}