server:
  port: ${env.APPLICATION_PORT:8080}
  servlet:
    context-path: "/car-rental"
  error:
    include-message: always   # Include error messages in the response
    include-binding-errors: always # Include binding errors in the response
    include-stacktrace: on-param # Show stack trace if requested with a parameter (e.g., ?trace=true)

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, swagger-ui"
  endpoint:
    health:
      show-details: always
  metrics: 
    enable:
      all: true
info: 
  env:
    enabled: true 
  app: 
    name: Car Rental API
    version: 0.0.1-SNAPSHOT
    description: "API for Rent your a car"
  metrics: 
    tags: rental-car-api

spring:
  application:
    name: car-rental-api
  datasource:
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    path: "/v3/api-docs"
  show-actuator: true

api:
  security:
    token:
      secret: ${env.JWT_SECRET:my-secret-key}